version: '3.8'

services:
  # 1. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./static:/usr/share/nginx/html/static
      - ./separated_music:/usr/share/nginx/html/separated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  # 2. API Server (Flask)
  api:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    expose:
      - "5000"

  # 3. Worker (Celery)
  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info -c 1
    volumes:
      - .:/app
    depends_on:
      - redis
      - api

  # 4. Task Queue (Redis)
  redis:
    image: redis:alpine
